[project]
name = "pairag"
version = "2.0.0"
requires-python = ">=3.11,<3.13"

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "if __name__ == .__main__.",
  "if TYPE_CHECKING:"
]

[tool.coverage.run]
source = ["backend"]
omit = [
  "backend/**/migrations/*",
  "backend/**/__main__.py",
  "backend/app/*",
  "backend/common/llm/openai/*",
  "backend/service/injection.py"
]

[tool.poetry]
name = "pairag"
version = "2.0.0"
description = "A short description of your project"
authors = ["Your Name <you@example.com>"]
packages = [
  {include = "db", from = "backend"},
  {include = "rag", from = "backend"},
  {include = "app", from = "backend"},
  {include = "api", from = "backend"},
  {include = "common", from = "backend"},
  {include = "extensions", from = "backend"},
  {include = "memory", from = "backend"},
  {include = "service", from = "backend"},
  {include = "tools", from = "backend"},
  {include = "evaluation", from = "backend"},
  {include = "utils", from = "backend"}
]

[tool.poetry.dependencies]
python = ">=3.11.0,<3.13"
fastapi = "0.115.2"
uvicorn = "^0.31.1"
llama-index-core = "^0.14.8"
llama-index-tools-mcp = "^0.4.3"
llama-index-embeddings-huggingface = "0.6.1"
llama-index-embeddings-openai-like = "^0.2.2"
llama-index-llms-openai = "^0.6.10"
llama-index-llms-openai-like = "^0.5.3"
llama-index-vector-stores-analyticdb = "^0.4.1"
llama-index-vector-stores-elasticsearch = "^0.5.1"
llama-index-vector-stores-milvus = "0.9.4"
llama-index-vector-stores-alibabacloud-opensearch = "^0.4.1"
llama-index-vector-stores-hologres = "^0.4.1"
llama-index-vector-stores-tablestore = "^0.3.1"
llama-index-vector-stores-postgres = "^0.7.2"
pydantic = "^2.7.0"
pytest = "^8.1.1"
flagembedding = "^1.2.10"
sentencepiece = "^0.2.0"
alibabacloud-oss-v2 = "^1.2.5"
asgi-correlation-id = "^4.3.1"
torch = "^2.6.0"
torchvision = "^0.21.0"
transformers = "4.51.3"
pytest-asyncio = "^0.23.7"
pytest-cov = "^5.0.0"
gunicorn = "^22.0.0"
modelscope = "^1.16.0"
asyncpg = "^0.29.0"
pgvector = "^0.3.2"
pre-commit = "^3.8.0"
bs4 = "^0.0.2"
httpx = "^0.28.1"
peft = "^0.12.0"
anyio = "^4.6.2.post1"
sqlparse = "^0.5.3"
func-timeout = "^4.3.5"
dashtext = "^0.0.7"
alibabacloud-iqs20241111 = "1.1.3"
alibabacloud-green20220302 = "^2.2.8"
serpapi = "^0.1.5"
alibabacloud-tea-openapi-sse = "^1.0.2"
pymilvus = "^2.6.4"
numpy = "1.26.4"
loguru = "^0.7.3"
opentelemetry-sdk = "^1.33.1"
sqlmodel = "^0.0.24"
mcp = {extras = ["cli"], version = "^1.22.0"}
# with bug fix, ref: https://github.com/Arize-ai/openinference/pull/2241
openinference-instrumentation-openai = "^0.1.39"
aiosqlite = "^0.21.0"
alembic = "^1.16.2"
celery = "^5.5.3"
chromadb = "^1.3.5"
redis = "^6.2.0"
tavily-python = "^0.7.12"
rapidfuzz = "^3.14.1"
xiyan-mcp-server = "^0.1.7"
json5 = "^0.12.1"
aiomysql = "^0.3.2"
aiofiles = "24.1.0"
alibabacloud-credentials = "1.0.1"
pairag-file = {path = "integrations/pairag-file", develop = true}
aiocache = "^0.12.3"
opentelemetry-instrumentation-fastapi = "^0.60b1"
opentelemetry-exporter-otlp-proto-http = "^1.39.1"
opentelemetry-exporter-otlp-proto-grpc = "^1.39.1"
pyyaml = "^6.0.2"
greenlet = "^3.3.1"
playwright = "^1.60.0"

[tool.pytest.ini_options]
asyncio_mode = "auto"
filterwarnings = [
  "ignore::DeprecationWarning"
]
