/*
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.aliyun.pairag.client.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ValidationErrorLocInner
 */
public class ValidationErrorLocInnerTest {
    private final ValidationErrorLocInner model = new ValidationErrorLocInner();

    /**
     * Model tests for ValidationErrorLocInner
     */
    @Test
    public void testValidationErrorLocInner() {
        // TODO: test ValidationErrorLocInner
    }

}
