# paragraph separator for splitter
DEFAULT_NODE_PARSER_TYPE = "Sentence"
DEFAULT_PARAGRAPH_SEP = "\n\n"
DEFAULT_SENTENCE_CHUNK_OVERLAP = 200
DEFAULT_SENTENCE_WINDOW_SIZE = 3
DEFAULT_BREAKPOINT = 95
DEFAULT_BUFFER_SIZE = 1
