// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import * as Toast from "@radix-ui/react-toast";

import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  icons: {
    icon: "/favicon.ico",
  },
  title: "PAIRAG",
  description: "Generated by create-assistant-ui",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <title>PAI-RAG</title>
        <link
          rel="icon"
          type="image/png"
          sizes="80x80"
          href="https://pai-rag.oss-cn-hangzhou.aliyuncs.com/logo/pairag_logo.png"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toast.Provider>{children}</Toast.Provider>
      </body>
    </html>
  );
}
