"""add chunk_config

Revision ID: 068d4e3eaf34
Revises: 1432eea7c5b9
Create Date: 2025-12-22 14:42:31.129006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db.op.safe_add import safe_add_column


# revision identifiers, used by Alembic.
revision: str = '068d4e3eaf34'
down_revision: Union[str, Sequence[str], None] = '1432eea7c5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    safe_add_column('pai_knowledgebase_file', sa.Column('chunk_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pai_knowledgebase_file', 'chunk_config')
    # ### end Alembic commands ###

