"""Add provider_name in model config

Revision ID: 1432eea7c5b9
Revises: 69b32d633f76
Create Date: 2025-12-11 20:05:07.817856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from db.op.safe_add import safe_add_column

# revision identifiers, used by Alembic.
revision: str = '1432eea7c5b9'
down_revision: Union[str, Sequence[str], None] = '69b32d633f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DASHSCOPE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    safe_add_column('pai_embedding_model', sa.Column('provider_name', sa.String(255), nullable=True))
    safe_add_column('pai_llm_model', sa.Column('model_name', sa.String(255), nullable=True))
    safe_add_column('pai_llm_model', sa.Column('provider_name', sa.String(255), nullable=True))
    safe_add_column('pai_reranker_model', sa.Column('provider_name', sa.String(255), nullable=True))

    safe_add_column('pai_knowledgebase', sa.Column('embedding_provider_name', sa.String(255), nullable=True))

    # 根据 base_url 自动更新 provider_name
    # pai_embedding_model
    op.execute(sa.text(f"UPDATE pai_embedding_model SET provider_name = 'dashscope' WHERE provider_name IS NULL AND endpoint = '{DASHSCOPE_URL}'"))
    op.execute(sa.text("UPDATE pai_embedding_model SET provider_name = 'openai_like' WHERE provider_name IS NULL"))

    # pai_llm_model
    op.execute(sa.text(f"UPDATE pai_llm_model SET provider_name = 'dashscope' WHERE provider_name IS NULL AND base_url = '{DASHSCOPE_URL}'"))
    op.execute(sa.text("UPDATE pai_llm_model SET provider_name = 'openai_like' WHERE provider_name IS NULL"))

    # pai_reranker_model
    op.execute(sa.text(f"UPDATE pai_reranker_model SET provider_name = 'dashscope' WHERE provider_name IS NULL AND base_url = '{DASHSCOPE_URL}'"))
    op.execute(sa.text("UPDATE pai_reranker_model SET provider_name = 'openai_like' WHERE provider_name IS NULL"))

    # pai_knowledgebase - 根据 embedding_model 的 provider_name 更新
    op.execute(sa.text("""
        UPDATE pai_knowledgebase kb
        SET embedding_provider_name = em.provider_name
        FROM pai_embedding_model em
        WHERE kb.embedding_model = em.model_id
        AND kb.tenant_id = em.tenant_id
        AND kb.embedding_provider_name IS NULL
    """))
    # 如果没有匹配到，默认设置为 openai_like
    op.execute(sa.text("UPDATE pai_knowledgebase SET embedding_provider_name = 'openai_like' WHERE embedding_provider_name IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('pai_reranker_model', 'provider_name')
    op.drop_column('pai_llm_model', 'provider_name')
    op.drop_column('pai_llm_model', 'model_name')
    op.drop_column('pai_embedding_model', 'provider_name')
    op.drop_column('pai_knowledgebase', 'embedding_provider_name')
    # ### end Alembic commands ###
