"""add app prompts

Revision ID: 1f5a4b9a7f29
Revises: b7e035c75b9d
Create Date: 2025-09-16 10:44:51.314437

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5a4b9a7f29'
down_revision: Union[str, Sequence[str], None] = 'b7e035c75b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def safe_add_column(table_name, column: sa.Column):
    # 先检查列是否存在（Sqlite 不支持add column if not exists）
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Get column info
    columns = inspector.get_columns(table_name)

    # Example: just get column names as a list
    column_names = [col['name'] for col in columns]

    if column.name not in column_names:
        op.add_column(
            table_name,
            column,
        )

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    safe_add_column('pai_chatbot_model', sa.Column('prompts', sa.JSON(), nullable=True))
    safe_add_column('pai_websearch_config', sa.Column('encrypted_tavily_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pai_websearch_config', 'encrypted_tavily_api_key')
    op.drop_column('pai_chatbot_model', 'prompts')
    # ### end Alembic commands ###
