"""fix fk constraint

Revision ID: 43592fc24169
Revises: 8e29cd385657
Create Date: 2025-10-20 15:20:32.279319

"""
from typing import Sequence, Union

from alembic import op
from db.op import safe_add
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43592fc24169'
down_revision: Union[str, Sequence[str], None] = '8e29cd385657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    safe_add.safe_add_column('pai_experiment_sample_entity', sa.Column('trace_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    # ### end Alembic commands ###
    op.drop_column('pai_experiment_sample_entity', 'trace_id')
