"""fix fk constraint

Revision ID: 43592fc24169
Revises: 8e29cd385657
Create Date: 2025-10-20 15:20:32.279319

"""
from typing import Sequence, Union

from alembic import op
from db.op import safe_add
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43592fc24169'
down_revision: Union[str, Sequence[str], None] = '8e29cd385657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.drop_constraint(op.f('pai_dataset_sample_dataset_id_fkey'), 'pai_dataset_sample', type_='foreignkey')
        op.create_foreign_key(None, 'pai_dataset_sample', 'pai_dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_evaluator_config_dataset_id_fkey'), 'pai_evaluator_config', type_='foreignkey')
        op.create_foreign_key(None, 'pai_evaluator_config', 'pai_dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_experiment_run_config_id_fkey'), 'pai_experiment', type_='foreignkey')
        op.drop_constraint(op.f('pai_experiment_evaluator_config_id_fkey'), 'pai_experiment', type_='foreignkey')
        op.drop_constraint(op.f('pai_experiment_dataset_id_fkey'), 'pai_experiment', type_='foreignkey')
        op.create_foreign_key(None, 'pai_experiment', 'pai_run_config', ['run_config_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'pai_experiment', 'pai_dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'pai_experiment', 'pai_evaluator_config', ['evaluator_config_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_experiment_sample_entity_experiment_id_fkey'), 'pai_experiment_sample_entity', type_='foreignkey')
        op.drop_constraint(op.f('pai_experiment_sample_entity_dataset_id_fkey'), 'pai_experiment_sample_entity', type_='foreignkey')
        op.drop_constraint(op.f('pai_experiment_sample_entity_sample_id_fkey'), 'pai_experiment_sample_entity', type_='foreignkey')
        op.create_foreign_key(None, 'pai_experiment_sample_entity', 'pai_dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'pai_experiment_sample_entity', 'pai_dataset_sample', ['sample_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'pai_experiment_sample_entity', 'pai_experiment', ['experiment_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_file_metadata_file_id_fkey'), 'pai_file_metadata', type_='foreignkey')
        op.drop_constraint(op.f('pai_file_metadata_metadata_id_fkey'), 'pai_file_metadata', type_='foreignkey')
        op.drop_constraint(op.f('pai_file_metadata_kb_id_fkey'), 'pai_file_metadata', type_='foreignkey')
        op.create_foreign_key(None, 'pai_file_metadata', 'pai_knowledgebase_metadata', ['metadata_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'pai_file_metadata', 'pai_knowledgebase', ['kb_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'pai_file_metadata', 'pai_knowledgebase_file', ['file_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_knowledgebase_chunk_file_id_fkey'), 'pai_knowledgebase_chunk', type_='foreignkey')
        op.drop_constraint(op.f('pai_knowledgebase_chunk_kb_id_fkey'), 'pai_knowledgebase_chunk', type_='foreignkey')
        op.create_foreign_key(None, 'pai_knowledgebase_chunk', 'pai_knowledgebase_file', ['file_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'pai_knowledgebase_chunk', 'pai_knowledgebase', ['kb_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_knowledgebase_file_kb_id_fkey'), 'pai_knowledgebase_file', type_='foreignkey')
        op.create_foreign_key(None, 'pai_knowledgebase_file', 'pai_knowledgebase', ['kb_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_knowledgebase_file_task_file_id_fkey'), 'pai_knowledgebase_file_task', type_='foreignkey')
        op.drop_constraint(op.f('pai_knowledgebase_file_task_kb_id_fkey'), 'pai_knowledgebase_file_task', type_='foreignkey')
        op.create_foreign_key(None, 'pai_knowledgebase_file_task', 'pai_knowledgebase', ['kb_id'], ['id'], ondelete='CASCADE')
        op.create_foreign_key(None, 'pai_knowledgebase_file_task', 'pai_knowledgebase_file', ['file_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_knowledgebase_metadata_kb_id_fkey'), 'pai_knowledgebase_metadata', type_='foreignkey')
        op.create_foreign_key(None, 'pai_knowledgebase_metadata', 'pai_knowledgebase', ['kb_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_permissions_role_id_fkey'), 'pai_permissions', type_='foreignkey')
        op.create_foreign_key(None, 'pai_permissions', 'pai_roles', ['role_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_run_config_dataset_id_fkey'), 'pai_run_config', type_='foreignkey')
        op.create_foreign_key(None, 'pai_run_config', 'pai_dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
        op.drop_constraint(op.f('pai_user_roles_role_id_fkey'), 'pai_user_roles', type_='foreignkey')
        op.create_foreign_key(None, 'pai_user_roles', 'pai_roles', ['role_id'], ['id'], ondelete='CASCADE')
    safe_add.safe_add_column('pai_experiment_sample_entity', sa.Column('trace_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        op.drop_constraint(None, 'pai_user_roles', type_='foreignkey')
        op.create_foreign_key(op.f('pai_user_roles_role_id_fkey'), 'pai_user_roles', 'pai_roles', ['role_id'], ['id'])
        op.drop_constraint(None, 'pai_run_config', type_='foreignkey')
        op.create_foreign_key(op.f('pai_run_config_dataset_id_fkey'), 'pai_run_config', 'pai_dataset', ['dataset_id'], ['id'])
        op.drop_constraint(None, 'pai_permissions', type_='foreignkey')
        op.create_foreign_key(op.f('pai_permissions_role_id_fkey'), 'pai_permissions', 'pai_roles', ['role_id'], ['id'])
        op.drop_constraint(None, 'pai_knowledgebase_metadata', type_='foreignkey')
        op.create_foreign_key(op.f('pai_knowledgebase_metadata_kb_id_fkey'), 'pai_knowledgebase_metadata', 'pai_knowledgebase', ['kb_id'], ['id'])
        op.drop_constraint(None, 'pai_knowledgebase_file_task', type_='foreignkey')
        op.drop_constraint(None, 'pai_knowledgebase_file_task', type_='foreignkey')
        op.create_foreign_key(op.f('pai_knowledgebase_file_task_kb_id_fkey'), 'pai_knowledgebase_file_task', 'pai_knowledgebase', ['kb_id'], ['id'])
        op.create_foreign_key(op.f('pai_knowledgebase_file_task_file_id_fkey'), 'pai_knowledgebase_file_task', 'pai_knowledgebase_file', ['file_id'], ['id'])
        op.drop_constraint(None, 'pai_knowledgebase_file', type_='foreignkey')
        op.create_foreign_key(op.f('pai_knowledgebase_file_kb_id_fkey'), 'pai_knowledgebase_file', 'pai_knowledgebase', ['kb_id'], ['id'])
        op.drop_constraint(None, 'pai_knowledgebase_chunk', type_='foreignkey')
        op.drop_constraint(None, 'pai_knowledgebase_chunk', type_='foreignkey')
        op.create_foreign_key(op.f('pai_knowledgebase_chunk_kb_id_fkey'), 'pai_knowledgebase_chunk', 'pai_knowledgebase', ['kb_id'], ['id'])
        op.create_foreign_key(op.f('pai_knowledgebase_chunk_file_id_fkey'), 'pai_knowledgebase_chunk', 'pai_knowledgebase_file', ['file_id'], ['id'])
        op.drop_constraint(None, 'pai_file_metadata', type_='foreignkey')
        op.drop_constraint(None, 'pai_file_metadata', type_='foreignkey')
        op.drop_constraint(None, 'pai_file_metadata', type_='foreignkey')
        op.create_foreign_key(op.f('pai_file_metadata_kb_id_fkey'), 'pai_file_metadata', 'pai_knowledgebase', ['kb_id'], ['id'])
        op.create_foreign_key(op.f('pai_file_metadata_metadata_id_fkey'), 'pai_file_metadata', 'pai_knowledgebase_metadata', ['metadata_id'], ['id'])
        op.create_foreign_key(op.f('pai_file_metadata_file_id_fkey'), 'pai_file_metadata', 'pai_knowledgebase_file', ['file_id'], ['id'])
        op.drop_constraint(None, 'pai_experiment_sample_entity', type_='foreignkey')
        op.drop_constraint(None, 'pai_experiment_sample_entity', type_='foreignkey')
        op.drop_constraint(None, 'pai_experiment_sample_entity', type_='foreignkey')
        op.create_foreign_key(op.f('pai_experiment_sample_entity_sample_id_fkey'), 'pai_experiment_sample_entity', 'pai_dataset_sample', ['sample_id'], ['id'])
        op.create_foreign_key(op.f('pai_experiment_sample_entity_dataset_id_fkey'), 'pai_experiment_sample_entity', 'pai_dataset', ['dataset_id'], ['id'])
        op.create_foreign_key(op.f('pai_experiment_sample_entity_experiment_id_fkey'), 'pai_experiment_sample_entity', 'pai_experiment', ['experiment_id'], ['id'])
        op.drop_constraint(None, 'pai_experiment', type_='foreignkey')
        op.drop_constraint(None, 'pai_experiment', type_='foreignkey')
        op.drop_constraint(None, 'pai_experiment', type_='foreignkey')
        op.create_foreign_key(op.f('pai_experiment_dataset_id_fkey'), 'pai_experiment', 'pai_dataset', ['dataset_id'], ['id'])
        op.create_foreign_key(op.f('pai_experiment_evaluator_config_id_fkey'), 'pai_experiment', 'pai_evaluator_config', ['evaluator_config_id'], ['id'])
        op.create_foreign_key(op.f('pai_experiment_run_config_id_fkey'), 'pai_experiment', 'pai_run_config', ['run_config_id'], ['id'])
        op.drop_constraint(None, 'pai_evaluator_config', type_='foreignkey')
        op.create_foreign_key(op.f('pai_evaluator_config_dataset_id_fkey'), 'pai_evaluator_config', 'pai_dataset', ['dataset_id'], ['id'])
        op.drop_constraint(None, 'pai_dataset_sample', type_='foreignkey')
        op.create_foreign_key(op.f('pai_dataset_sample_dataset_id_fkey'), 'pai_dataset_sample', 'pai_dataset', ['dataset_id'], ['id'])
    # ### end Alembic commands ###
    op.drop_column('pai_experiment_sample_entity', 'trace_id')
