"""init

Revision ID: 53a6321067d4
Revises: 
Create Date: 2025-08-26 13:12:47.456714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53a6321067d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def safe_add_column(table_name, column: sa.Column):
    # 先检查列是否存在（Sqlite 不支持add column if not exists）
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Get column info
    columns = inspector.get_columns(table_name)

    # Example: just get column names as a list
    column_names = [col['name'] for col in columns]

    if column.name not in column_names:
        op.add_column(
            table_name,
            column,
        )

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    safe_add_column("pai_chatbot_model", sa.Column('enable_input_guardrail', sa.Boolean(), nullable=True))
    safe_add_column("pai_chatbot_model", sa.Column('enable_output_guardrail', sa.Boolean(), nullable=True))
    safe_add_column("pai_chatbot_model", sa.Column('guardrail_hint', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pai_chatbot_model', 'guardrail_hint')
    op.drop_column('pai_chatbot_model', 'enable_output_guardrail')
    op.drop_column('pai_chatbot_model', 'enable_input_guardrail')
    # ### end Alembic commands ###
