"""init

Revision ID: 53a6321067d4
Revises: 
Create Date: 2025-08-26 13:12:47.456714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53a6321067d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pai_guardrail_config',
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('encrypted_access_key_id', sa.String(), nullable=False),
    sa.Column('encrypted_access_key_secret', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pai_chatbot_model', sa.Column('enable_input_guardrail', sa.Boolean(), nullable=True))
    op.add_column('pai_chatbot_model', sa.Column('enable_output_guardrail', sa.Boolean(), nullable=True))
    op.add_column('pai_chatbot_model', sa.Column('guardrail_hint', sa.String(), nullable=True))
    op.alter_column('pai_config_change_event', 'event_type',
               existing_type=postgresql.ENUM('ADD', 'DELETE', 'UPDATE', name='changeeventtype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('pai_config_change_event', 'event_source',
               existing_type=postgresql.ENUM('EMBEDDING', 'LLM', 'RERANK', 'KNOWLEDGEBASE', 'MCP', 'TRACE', 'WEBSEARCH', 'CHATBOT', 'PROMPT', name='changeeventsource'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pai_config_change_event', 'event_source',
               existing_type=sa.String(),
               type_=postgresql.ENUM('EMBEDDING', 'LLM', 'RERANK', 'KNOWLEDGEBASE', 'MCP', 'TRACE', 'WEBSEARCH', 'CHATBOT', 'PROMPT', name='changeeventsource'),
               existing_nullable=False)
    op.alter_column('pai_config_change_event', 'event_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ADD', 'DELETE', 'UPDATE', name='changeeventtype'),
               existing_nullable=False)
    op.drop_column('pai_chatbot_model', 'guardrail_hint')
    op.drop_column('pai_chatbot_model', 'enable_output_guardrail')
    op.drop_column('pai_chatbot_model', 'enable_input_guardrail')
    op.drop_table('pai_guardrail_config')
    # ### end Alembic commands ###
