"""add rerank type

Revision ID: 85ddcf286b9c
Revises: bfe08f8125ce
Create Date: 2025-11-26 14:58:37.286825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.op.safe_add import safe_add_column


# revision identifiers, used by Alembic.
revision: str = '85ddcf286b9c'
down_revision: Union[str, Sequence[str], None] = 'bfe08f8125ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    safe_add_column("pai_reranker_model", sa.Column('type', sa.String(), nullable=True))
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pai_reranker_model', 'type')
    # ### end Alembic commands ###
