"""split file

Revision ID: 8e29cd385657
Revises: 1f5a4b9a7f29
Create Date: 2025-10-15 17:16:18.671183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db.op.safe_add import safe_add_column


# revision identifiers, used by Alembic.
revision: str = '8e29cd385657'
down_revision: Union[str, Sequence[str], None] = '1f5a4b9a7f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    safe_add_column('pai_knowledgebase_chunk', sa.Column('file_part', sa.Integer(), nullable=True, default=0))
    safe_add_column('pai_knowledgebase_chunk', sa.Column('file_version', sa.Integer(), nullable=True, default=0))
    safe_add_column('pai_knowledgebase_file', sa.Column('file_version', sa.Integer(), nullable=True, default=0))
    safe_add_column('pai_run_config', sa.Column('prompts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pai_run_config', 'prompts')
    op.drop_column('pai_knowledgebase_file', 'file_version')
    op.drop_column('pai_knowledgebase_chunk', 'file_version')
    op.drop_column('pai_knowledgebase_chunk', 'file_part')
    # ### end Alembic commands ###
