"""add enable_faq and faq table

Revision ID: 93f02e32f851
Revises: 068d4e3eaf34
Create Date: 2025-12-25 16:03:26.237567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db.op.safe_add import safe_add_column


# revision identifiers, used by Alembic.
revision: str = '93f02e32f851'
down_revision: Union[str, Sequence[str], None] = '068d4e3eaf34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create pai_chatbot_faq_config table (FAQ configuration)
    op.create_table(
        'pai_chatbot_faq_config',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('chatbot_id', sa.String(), nullable=True),
        sa.Column('tenant_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pai_chatbot_faq_config_chatbot_id', 'pai_chatbot_faq_config', ['chatbot_id'], unique=False)
    op.create_index('ix_pai_chatbot_faq_config_tenant_id', 'pai_chatbot_faq_config', ['tenant_id'], unique=False)
    
    # Create pai_chatbot_faq table (FAQ items)
    op.create_table(
        'pai_chatbot_faq',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('question', sa.Text(), nullable=True),
        sa.Column('answer', sa.Text(), nullable=True),
        sa.Column('chatbot_id', sa.String(), nullable=True),
        sa.Column('file_id', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True, default=True),
        sa.Column('tenant_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pai_chatbot_faq_chatbot_id', 'pai_chatbot_faq', ['chatbot_id'], unique=False)
    op.create_index('ix_pai_chatbot_faq_tenant_id', 'pai_chatbot_faq', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pai_chatbot_faq_tenant_id', table_name='pai_chatbot_faq')
    op.drop_index('ix_pai_chatbot_faq_chatbot_id', table_name='pai_chatbot_faq')
    op.drop_table('pai_chatbot_faq')
    op.drop_index('ix_pai_chatbot_faq_config_tenant_id', table_name='pai_chatbot_faq_config')
    op.drop_index('ix_pai_chatbot_faq_config_chatbot_id', table_name='pai_chatbot_faq_config')
    op.drop_table('pai_chatbot_faq_config')
    # ### end Alembic commands ###

