"""Add chunk index

Revision ID: b7e035c75b9d
Revises: 53a6321067d4
Create Date: 2025-08-28 19:41:37.341122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e035c75b9d'
down_revision: Union[str, Sequence[str], None] = '53a6321067d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pai_knowledgebase_chunk', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('pai_message', sa.Column('local_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pai_knowledgebase_chunk', 'index')
    op.drop_column('pai_message', 'local_id')
    # ### end Alembic commands ###
