"""add enable_chatdb

Revision ID: bfe08f8125ce
Revises: 43592fc24169
Create Date: 2025-10-22 19:05:37.654151

"""
from typing import Sequence, Union

from alembic import op
from db.op.safe_add import safe_add_column
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe08f8125ce'
down_revision: Union[str, Sequence[str], None] = '43592fc24169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    safe_add_column('pai_chatbot_model', sa.Column('enable_chatdb', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.drop_column('pai_chatbot_model', 'enable_chatdb')
