services:
  api:
    image: mybigpai-public-registry.cn-beijing.cr.aliyuncs.com/mybigpai/pairag:1.1.0
    ports:
      - "8680:8680"
    restart: always
    environment:
      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY}
      OSS_ACCESS_KEY_ID: ${OSS_ACCESS_KEY_ID}
      OSS_ACCESS_KEY_SECRET: ${OSS_ACCESS_KEY_SECRET}
      PAIRAG_RAG__oss_store__bucket: ${OSS_BUCKET}
      PAIRAG_RAG__oss_store__endpoint: ${OSS_ENDPOINT:-oss-cn-hangzhou.aliyuncs.com}
      ARMS_APP_NAME: ${ARMS_APP_NAME}
      ARMS_REGION_ID: ${ARMS_REGION_ID}
      ARMS_LICENSE_KEY: ${ARMS_LICENSE_KEY}
      ARMS_IS_PUBLIC: true
      ENABLE_FASTAPI: false
      ENABLE_REQUESTS: false
      ENABLE_AIOHTTPCLIENT: false
      ENABLE_HTTPX: false
      LD_LIBRARY_PATH: /usr/local/lib

    volumes:
      - ../model_repository:/app/model_repository
      - ./app_data:/app/localdata
    entrypoint: ["./scripts/start.sh", "-w", "1"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8680/api/v1/health"]
      interval: 30s
      retries: 40
      start_period: 20s
