ACCEPTABLE_DOC_TYPES = set(
    [
        ".html",
        ".htm",
        ".txt",
        ".docx",
        ".pdf",
        ".pptx",
        ".faq",
        ".md",
        ".xls",
        ".jsonl",
        ".csv",
        ".xlsx",
        ".jpg",
        ".jpeg",
        ".png",
    ]
)
