"""baseline schema

Revision ID: 6ccd93a32c2e
Revises:
Create Date: 2026-07-09 01:24:32.771923+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated columns reference sqlmodel.sql.sqltypes.*


# revision identifiers, used by Alembic.
revision: str = '6ccd93a32c2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('response_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_items_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_items_response_id'), ['response_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_items_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('last_response_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summarized_seq', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('knowledge_bases',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('default_parser_config', sa.JSON(), nullable=True),
    sa.Column('default_retrieval_config', sa.JSON(), nullable=True),
    sa.Column('embedding_config', sa.JSON(), nullable=True),
    sa.Column('vector_store_config', sa.JSON(), nullable=True),
    sa.Column('keyword_index_config', sa.JSON(), nullable=True),
    sa.Column('rerank_config', sa.JSON(), nullable=True),
    sa.Column('active_index_version_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_bases_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_bases_status'), ['status'], unique=False)

    op.create_table('knowledge_chunks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('heading_path', sa.JSON(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_ref', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_indexed_at'), ['indexed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_chunks_status'), ['status'], unique=False)

    op.create_table('knowledge_data_sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('source_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('source_config', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_schedule', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('last_sync_report', sa.JSON(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_data_sources_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_data_sources_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_data_sources_source_key'), ['source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_data_sources_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_data_sources_status'), ['status'], unique=False)

    op.create_table('knowledge_documents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('system_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_documents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_indexed_at'), ['indexed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_documents_status'), ['status'], unique=False)

    op.create_table('knowledge_index_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('embedding_provider_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('vector_store_provider_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('vector_index_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('vector_namespace', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('keyword_index_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_index_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_index_versions_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_index_versions_status'), ['status'], unique=False)

    op.create_table('knowledge_ingestion_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('triggered_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('succeeded_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_ingestion_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_ingestion_jobs_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_ingestion_jobs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_ingestion_jobs_status'), ['status'], unique=False)

    op.create_table('memory_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('source_response_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_items_user_id'), ['user_id'], unique=False)

    op.create_table('responses',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('previous_response_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_previous_response_id'), ['previous_response_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('invite_token_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_previous_response_id'))
        batch_op.drop_index(batch_op.f('ix_responses_conversation_id'))

    op.drop_table('responses')
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_items_user_id'))

    op.drop_table('memory_items')
    with op.batch_alter_table('knowledge_ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_ingestion_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_ingestion_jobs_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_ingestion_jobs_kb_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_ingestion_jobs_document_id'))

    op.drop_table('knowledge_ingestion_jobs')
    with op.batch_alter_table('knowledge_index_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_index_versions_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_index_versions_kb_id'))

    op.drop_table('knowledge_index_versions')
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_source_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_kb_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_indexed_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_content_hash'))
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_category'))

    op.drop_table('knowledge_documents')
    with op.batch_alter_table('knowledge_data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_data_sources_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_data_sources_source_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_data_sources_source_key'))
        batch_op.drop_index(batch_op.f('ix_knowledge_data_sources_kb_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_data_sources_deleted_at'))

    op.drop_table('knowledge_data_sources')
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_kb_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_indexed_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_chunks_deleted_at'))

    op.drop_table('knowledge_chunks')
    with op.batch_alter_table('knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_bases_deleted_at'))

    op.drop_table('knowledge_bases')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('conversation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_items_response_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_items_conversation_id'))

    op.drop_table('conversation_items')
    # ### end Alembic commands ###
