"""app config documents

Revision ID: 9a4e7b2c1d30
Revises: c4e8f1a9b3d7
Create Date: 2026-07-12 18:15:00.000000+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated columns reference sqlmodel.sql.sqltypes.*


# revision identifiers, used by Alembic.
revision: str = "9a4e7b2c1d30"
down_revision: Union[str, None] = "c4e8f1a9b3d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "app_config_documents",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("document_json", sa.JSON(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("checksum", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("app_config_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_app_config_documents_revision"), ["revision"], unique=False
        )

    op.create_table(
        "app_config_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("document_json", sa.JSON(), nullable=True),
        sa.Column("checksum", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("app_config_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_app_config_revisions_config_id"), ["config_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_app_config_revisions_revision"), ["revision"], unique=False
        )


def downgrade() -> None:
    with op.batch_alter_table("app_config_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_app_config_revisions_revision"))
        batch_op.drop_index(batch_op.f("ix_app_config_revisions_config_id"))
    op.drop_table("app_config_revisions")

    with op.batch_alter_table("app_config_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_app_config_documents_revision"))
    op.drop_table("app_config_documents")
