"""background jobs queue

Revision ID: b7f3a9c1d2e4
Revises: 6ccd93a32c2e
Create Date: 2026-07-09 15:00:00.000000+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated columns reference sqlmodel.sql.sqltypes.*


# revision identifiers, used by Alembic.
revision: str = 'b7f3a9c1d2e4'
down_revision: Union[str, None] = '6ccd93a32c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'background_jobs',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=True),
        sa.Column('result', sa.JSON(), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('max_attempts', sa.Integer(), nullable=False),
        sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_kb_id'), ['kb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_created_by'), ['created_by'], unique=False)


def downgrade() -> None:
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_created_by'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_kb_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_run_after'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_kind'))
    op.drop_table('background_jobs')
