"""knowledge document contents (verbatim ingested text)

Revision ID: c4e8f1a9b3d7
Revises: b7f3a9c1d2e4
Create Date: 2026-07-09 22:10:00.000000+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated columns reference sqlmodel.sql.sqltypes.*


# revision identifiers, used by Alembic.
revision: str = 'c4e8f1a9b3d7'
down_revision: Union[str, None] = 'b7f3a9c1d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'knowledge_document_contents',
        sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('kb_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column('char_len', sa.Integer(), nullable=False),
        sa.Column('truncated', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('document_id'),
    )
    with op.batch_alter_table('knowledge_document_contents', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_knowledge_document_contents_kb_id'), ['kb_id'], unique=False
        )


def downgrade() -> None:
    with op.batch_alter_table('knowledge_document_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_document_contents_kb_id'))
    op.drop_table('knowledge_document_contents')
