"""add mcp need_token

Revision ID: 67a821bb8b09
Revises: c2effc28f553
Create Date: 2025-06-19 11:01:54.855899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a821bb8b09'
down_revision: Union[str, None] = 'c2effc28f553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pai_mcp_server', sa.Column('need_token', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pai_mcp_server', 'need_token')
    # ### end Alembic commands ###
