DEFAULT_CHUNK_SIZE = 1024
DEFAULT_CHUNK_OVERLAP = 50
DEFAULT_PARSER_TYPE = "structure"
DEFAULT_SENTENCE_SEPARATOR = "\n\n"

DEFAULT_EMBEDDING_MODEL = "BAAI/bge-m3"
DEFAULT_RERANK_MODEL = "BAAI/bge-reranker-v2-m3"

DEFAULT_SIMILARITY_TOP_K = 5
DEFAULT_SIMILARITY_THRESHOLD = 0.5

DEFAULT_RERANK_SIMILARITY_TOP_K = 5
DEFAULT_RERANK_SIMILARITY_THRESHOLD = 0.5


DEFAULT_KNOWLEDGEBASE_PATH = "localdata/knowledgebases"
ATTACHMENT_KNOWLEDGEBASE_NAME = "default_attachments"
DEFAULT_VECTOR_ID = "default_vectordb"


DEFAULT_METADATA_KEYS = [
    "file_name",
    "file_path",
    "file_size",
    "file_extension",
    "file_url",
    "doc_id",
  ]
