from pairag.utils.constants import try_get_int_env


MAX_CHAT_STEPS = try_get_int_env("MAX_CHAT_STEPS", 15)

DEFAULT_MAX_INPUT_TOKENS = 20000
DEFAULT_HISTORY_MESSAGES_COUNT = 10
DEFAULT_HISTORY_MESSAGES_INPUT_TOKENS = 2000
