name: PR Build

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - feature
      - "releases/**"

concurrency:
  group: pr-build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.11"
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: "x64"

      - name: Set up redis-server
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: "7.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install poetry
          poetry env activate
          poetry install

      - name: Run Linter
        shell: bash
        run: |
          poetry run pip install pre-commit
          poetry run make lint

      - name: Run Tests
        run: |
          poetry run make coveragetest
        env:
          DASHSCOPE_API_KEY: ${{ secrets.TESTDASHSCOPEKEY }}
          PAIRAG_RAG__embedding__source: "huggingface"
          PAIRAG_RAG__llm__source: "DashScope"
          PAIRAG_RAG__llm__model: "qwen-max"
          BING_SEARCH_KEY: ${{ secrets.BING_SEARCH_KEY }}
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          TRACE_TOKEN: ${{ secrets.TRACE_TOKEN }}
          DISABLE_REDIS_CACHE_IN_TESTS: "true"
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

      - name: Get Cover
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: localdata/test_output/coverage_report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          # thresholdAll: 0.4 # Total coverage threshold
          #thresholdNew: 0.9 # New files coverage threshold
          #thresholdModified: 0.9 # Modified files coverage threshold
